spring.application.name=demo

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# База данных
spring.datasource.url=jdbc:h2:file:./data/moviediary
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

jwt.secret=mySecretKey12345mySecretKey12345mySecretKey12345